### ISSUE TITLE
Can't see the banner to publish

### ISSUE THREAD

**Issue by meekdenzo** [meekdenzo/vrd#2]
@Trott Not sure what the problem is here, but I can't see the banner to publish the action to GitHub Marketplace as per https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#:~:text=When%20a%20repository%20contains%20an%20action%20metadata%20file%20(action.yml%20or%20action.yaml)%2C%20you%27ll%20see%20a%20banner%20to%20publish%20the%20action%20to%20GitHub%20Marketplace.%20Click%20Draft%20a%20release.

**Comment by Trott** [comment]
It seems like the `action.yml` file is misformatted? The `runs:` entry has a space before it which would seem to make the file invalid (IIUC). Maybe that's the problem?

**Comment by meekdenzo** [comment]
> It seems like the `action.yml` file is misformatted? The `runs:` entry has a space before it which would seem to make the file invalid (IIUC). Maybe that's the problem?

You're good lol
